#!/bin/sh
lock() {
	i3lock -c 000000
#	light-locker-command -l
#	xdg-screensaver lock
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock
	sudo pm-suspend
        ;;
    hibernate)
        lock
	sudo pm-hibernate
        ;;
    reboot)
        sudo shutdown -r now
        ;;
    shutdown)
        sudo shutdown -h now
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
